### ISSUE TITLE
EWD Article: How the Epic Stack Makes You Faster

### ISSUE THREAD

**Issue by kentcdodds** [skillrecordings/products#1260]
https://epic-web.sanity.studio/desk/articles;a65815bd-4899-469e-b13e-98df2512485a

**Comment by vojtaholik** [comment]
https://www.epicweb.dev/how-the-epic-stack-makes-you-faster
<img src="https://github.com/skillrecordings/products/assets/25487857/738095ee-f4e7-4b99-952e-2aea62c1325e" width="500" alt="share card">

**Comment by kentcdodds** [comment]
That looks sick!
