### ISSUE TITLE
Book Feedback: Table of contents

### ISSUE THREAD

**Issue by mattpocock** [skillrecordings/products#1540]
Table of contents should be more discoverable on desktop. Should either show by default, or have a hint pointing it out.

**Comment by vojtaholik** [comment]
I made this sidebar ToC the default and added the ability to toggle to the other one that centers the text.

<img src="https://github.com/skillrecordings/products/assets/25487857/d5ee67f2-5530-4a01-ba3f-ea58376f64f3" width="500" alt="screenshot">
