### ISSUE TITLE
Book Feedback: Exercises

### ISSUE THREAD

**Issue by mattpocock** [skillrecordings/products#1542]
Need to figure out the proper flow for exercises for the book.

I like the idea of an 'open in VSCode' button that opens the correct exercise in their IDE. I have had this idea for a while, but need a bit of engineering to get there:

1. Users would need to install a VSCode extension.
2. The first time they press 'open in VSCode', they would be prompted either to clone the repo or locate where it is on their file system.
3. Future 'open in VSCode' presses would open the correct file

This also needs to be figured out for the paper book.

**Comment by vojtaholik** [comment]
prototype screenshot for future reference:
<img src="https://github.com/skillrecordings/products/assets/25487857/4fc13c26-6f60-4646-a01b-e17c9eac5e37" width="350" alt="prototype">
