### ISSUE TITLE
code for typescriptcourse?

### ISSUE THREAD

**Issue by jsjoeio** [skillrecordings/products#1686]
yo @joelhooks! hope all is well!

i saw the team moved some stuff around in https://github.com/skillrecordings/products/pull/1296

where is the new home for typescriptcourse? i searched in the org but didn't see it.

reasoning: someone reached out and said they can't access the content. i don't see any network requests or console errors so not totally sure what's happening. would love some help! 

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/6dcff65c-b8ce-41a0-87f9-1173357f4b1c">

**Comment by joelhooks** [comment]
it's been archived and is no longer available in a public repository
