### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by mattpocock** [skillrecordings/products#1692]
https://totaltypescript.sanity.studio/structure/articles;25cd9b2e-e208-447a-91e6-21db45c23dd9%2Ctemplate%3Darticle

**Comment by vojtaholik** [comment]
https://totaltypescript.com/how-to-create-an-npm-package
![how-to-create-an-npm-package](https://github.com/user-attachments/assets/fc10f284-5bae-4846-bad4-31829e5f4c03)
