### ISSUE TITLE
Article: Arr Element

### ISSUE THREAD

**Issue by mattpocock** [skillrecordings/products#1709]
https://totaltypescript.sanity.studio/structure/articles;d7b71563-5d55-48cb-8474-e911d0b913ca%2Ctemplate%3Darticle

**Comment by vojtaholik** [comment]
https://www.totaltypescript.com/get-the-type-of-an-array-element
![get-the-type-of-an-array-element](https://github.com/user-attachments/assets/ab15ca7e-7dc5-42e1-b28b-b606460e833d)
