### ISSUE TITLE
TypeScript Course: Remove FOUC?

### ISSUE THREAD

**Issue by jsjoeio** [skillrecordings/products#175]
## Suggestion

Add `font-display:optional` to the TypeScript Course website to "remove the font jank" (probably FOUC?)

Suggested: https://twitter.com/jaredpalmer/status/1499499872931782661

**Comment by vojtaholik** [comment]
I actually got this fixed earlier today :) https://github.com/skillrecordings/products/commit/af5dd0a5338201daa7fad4de1180771a8cb2b84c
seems super smooth now.
<img src="https://user-images.githubusercontent.com/25487857/156823179-7a2ac200-1063-41e8-89e2-107fb1acac8d.png" width="250" alt="lighthouse score">
