### ISSUE TITLE
Breadcrumbs are using generic names for lessons

### ISSUE THREAD

**Issue by Creeland** [skillrecordings/products#283]
**This isn't necessarily a problem** but I did want to make note of this. In the breadcrumbs, a generic title based on the lesson index is used instead of the lesson's actual title

![Screen Shot 2022-06-28 at 5 10 05 PM](https://user-images.githubusercontent.com/518406/176309893-971ac2c9-c0b0-4e4a-9cbf-5c0c272a7dae.png)

**Comment by vojtaholik** [comment]
this is by design :) no need to repeat lesson title twice below each other.
