### ISSUE TITLE
[Testing Accessibility] Accessibility of Course Certificate PDF

### ISSUE THREAD

**Issue by marcysutton** [skillrecordings/products#305]
We need to ensure the course certificates are as accessible as can be. For PDF documents, this means enabling tagging to expose headings, alt text, and whatever else can be exposed accessibly.

Adobe Acrobat has an Accessibility Checker built in that can help highlight issues. My question is: what control do we have over the PDFs that get generated?

Example certificate: [Testing Accessibility Certificate - Marcy Sutton.pdf](https://github.com/skillrecordings/products/files/9077830/Testing.Accessibility.Certificate.-.Marcy.Sutton.pdf)

Here are some tips: https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html

Here's the report:

<h1 id="reportTop" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Accessibility Report</h1><dl style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Filename:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;">Testing Accessibility Certificate - Marcy Sutton.pdf</dd></dl><dl style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Report created by:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;">Marcy Sutton</dd><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Organization:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;"></dd></dl><p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">[Personal and organization information from the Preferences &gt; Identity dialog.]</p><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Summary</h2><p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">The checker found problems which may prevent the document from being fully accessible.</p><ul style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><li style="list-style: square;">Needs manual check: 2</li><li style="list-style: square;">Passed manually: 0</li><li style="list-style: square;">Failed manually: 0</li><li style="list-style: square;">Skipped: 1</li><li style="list-style: square;">Passed: 12</li><li style="list-style: square;">Failed: 17</li></ul><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Detailed Report</h2>

Document
--

Accessibility permission flag | Passed | Accessibility permission flag must be set
Image-only PDF | Passed | Document is not image-only PDF
Tagged PDF | Failed | Document is tagged PDF
Logical Reading Order | Needs manual check | Document structure provides a logical reading order
Primary language | Failed | Text language is specified
Title | Failed | Document title is showing in title bar
Bookmarks | Passed | Bookmarks are present in large documents
Color contrast | Needs manual check | Document has appropriate color contrast
Page Content

Tagged content | Failed | All page content is tagged
Tagged annotations | Passed | All annotations are tagged
Tab order | Failed | Tab order is consistent with structure order
Character encoding | Passed | Reliable character encoding is provided
Tagged multimedia | Passed | All multimedia objects are tagged
Screen flicker | Passed | Page will not cause screen flicker
Scripts | Passed | No inaccessible scripts
Timed responses | Passed | Page does not require timed responses
Navigation links | Passed | Navigation links are not repetitive
Forms

Tagged form fields | Passed | All form fields are tagged
Field descriptions | Passed | All form fields have description
Alternate Text

Figures alternate text | Failed | Figures require alternate text
Nested alternate text | Failed | Alternate text that will never be read
Associated with content | Failed | Alternate text must be associated with some content
Hides annotation | Failed | Alternate text should not hide annotation
Other elements alternate text | Failed | Other elements that require alternate text
Tables

Rows | Failed | TR must be a child of Table, THead, TBody, or TFoot
TH and TD | Failed | TH and TD must be children of TR
Headers | Failed | Tables should have headers
Regularity | Failed | Tables must contain the same number of columns in each row and rows in each column
Summary | Skipped | Tables must have a summary
Lists

List items | Failed | LI must be a child of L
Lbl and LBody | Failed | Lbl and LBody must be children of LI
Headings

Appropriate nesting | Failed | Appropriate nesting

<hr style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><a href="#reportTop" style="font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;"></a><br class="Apple-interchange-newline">Accessibility Report

Filename:
Testing Accessibility Certificate - Marcy Sutton.pdf
Report created by:
Marcy Sutton
Organization:
[Personal and organization information from the Preferences > Identity dialog.]

Summary

The checker found problems which may prevent the document from being fully accessible.

Needs manual check: 2
Passed manually: 0
Failed manually: 0
Skipped: 1
Passed: 12
Failed: 17
Detailed Report

Document
Rule Name	Status	Description
[Accessibility permission flag](http://www.adobe.com/go/acrobat11_accessibility_checker_en#Perms)	Passed	Accessibility permission flag must be set
[Image-only PDF](http://www.adobe.com/go/acrobat11_accessibility_checker_en#ImageOnlyPDF)	Passed	Document is not image-only PDF
[Tagged PDF](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TaggedPDF)	Failed	Document is tagged PDF
[Logical Reading Order](http://www.adobe.com/go/acrobat11_accessibility_checker_en#LogicalRO)	Needs manual check	Document structure provides a logical reading order
[Primary language](http://www.adobe.com/go/acrobat11_accessibility_checker_en#PrimeLang)	Failed	Text language is specified
[Title](http://www.adobe.com/go/acrobat11_accessibility_checker_en#DocTitle)	Failed	Document title is showing in title bar
[Bookmarks](http://www.adobe.com/go/acrobat11_accessibility_checker_en#Bookmarks)	Passed	Bookmarks are present in large documents
[Color contrast](http://www.adobe.com/go/acrobat11_accessibility_checker_en#ColorContrast)	Needs manual check	Document has appropriate color contrast
Page Content
Rule Name	Status	Description
[Tagged content](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TaggedCont)	Failed	All page content is tagged
[Tagged annotations](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TaggedAnnots)	Passed	All annotations are tagged
[Tab order](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TabOrder)	Failed	Tab order is consistent with structure order
[Character encoding](http://www.adobe.com/go/acrobat11_accessibility_checker_en#CharEnc)	Passed	Reliable character encoding is provided
[Tagged multimedia](http://www.adobe.com/go/acrobat11_accessibility_checker_en#Multimedia)	Passed	All multimedia objects are tagged
[Screen flicker](http://www.adobe.com/go/acrobat11_accessibility_checker_en#FlickerRate)	Passed	Page will not cause screen flicker
[Scripts](http://www.adobe.com/go/acrobat11_accessibility_checker_en#Scripts)	Passed	No inaccessible scripts
[Timed responses](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TimedResponses)	Passed	Page does not require timed responses
[Navigation links](http://www.adobe.com/go/acrobat11_accessibility_checker_en#NavLinks)	Passed	Navigation links are not repetitive
Forms
Rule Name	Status	Description
[Tagged form fields](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TaggedFormFields)	Passed	All form fields are tagged
[Field descriptions](http://www.adobe.com/go/acrobat11_accessibility_checker_en#FormFieldNames)	Passed	All form fields have description
Alternate Text
Rule Name	Status	Description
[Figures alternate text](http://www.adobe.com/go/acrobat11_accessibility_checker_en#FigAltText)	Failed	Figures require alternate text
[Nested alternate text](http://www.adobe.com/go/acrobat11_accessibility_checker_en#NestedAltText)	Failed	Alternate text that will never be read
[Associated with content](http://www.adobe.com/go/acrobat11_accessibility_checker_en#AltTextNoContent)	Failed	Alternate text must be associated with some content
[Hides annotation](http://www.adobe.com/go/acrobat11_accessibility_checker_en#HiddenAnnot)	Failed	Alternate text should not hide annotation
[Other elements alternate text](http://www.adobe.com/go/acrobat11_accessibility_checker_en#OtherAltText)	Failed	Other elements that require alternate text
Tables
Rule Name	Status	Description
[Rows](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TableRows)	Failed	TR must be a child of Table, THead, TBody, or TFoot
[TH and TD](http://www.adobe.com/go/acrobat11_accessibility_checker_en#THTD)	Failed	TH and TD must be children of TR
[Headers](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TableHeaders)	Failed	Tables should have headers
[Regularity](http://www.adobe.com/go/acrobat11_accessibility_checker_en#RegularTable)	Failed	Tables must contain the same number of columns in each row and rows in each column
[Summary](http://www.adobe.com/go/acrobat11_accessibility_checker_en#TableSummary)	Skipped	Tables must have a summary
Lists
Rule Name	Status	Description
[List items](http://www.adobe.com/go/acrobat11_accessibility_checker_en#ListItems)	Failed	LI must be a child of L
[Lbl and LBody](http://www.adobe.com/go/acrobat11_accessibility_checker_en#LblLBody)	Failed	Lbl and LBody must be children of LI
Headings
Rule Name	Status	Description
[Appropriate nesting](http://www.adobe.com/go/acrobat11_accessibility_checker_en#Headings)	Failed	Appropriate nesting

**Comment by vojtaholik** [comment]
Code used to generate the PDF: https://github.com/skillrecordings/products/blob/main/apps/testingaccessibility/src/utils/draw-certificate.ts

I'll need to research what's possible with this setup in terms of a11y.

**Comment by vojtaholik** [comment]
include document title in pdf metadata: https://github.com/skillrecordings/products/commit/898aee7f096b4ca1cd29aee43fad8d612f4cff57

this change does pass in https://checkers.eiii.eu/en/pdfcheck/ but does not in adobe acrobat.

**Comment by marcysutton** [comment]
Hmmmm. Can we do anything to add structure to it, i.e. the section of the PDFKit docs on "Tags and Structure Element Types"? When I tried navigating the PDF with VoiceOver and Preview, none of the text is read at all. 

PDFs are allegedly one big image until you tag them, and then they get essentially an image map with text exposed. It's a real mess of a format for accessibility under the hood, despite being super convenient otherwise.

Another idea would be to create a webpage of the certificate that people could optionally print / save as a PDF?

**Comment by marcysutton** [comment]
I asked in the web-a11y Slack and got this response re: Acrobat checks and the title:

> Honestly, I've always found title and the accessibility checker to always fail even when a title is present.

**Comment by joelhooks** [comment]
we ended up just making the certs a web page
