### ISSUE TITLE
[Total TypeScript] Brief flash of unstyled content on home page

### ISSUE THREAD

**Issue by mattpocock** [skillrecordings/products#659]
I imagine this could be fixed with next/fonts or next/image.

**Comment by vojtaholik** [comment]
@mattpocock could you please capture the behavior in a gif or video?

**Comment by vojtaholik** [comment]
I see now — looks like it's related to loading fonts. we'll tee up an upgrade to next 13 and use next/fonts 👍

**Comment by mattpocock** [comment]
Don't see this any more.
