### ISSUE TITLE
Incorrect quiz link

### ISSUE THREAD

**Issue by laurieontech** [skillrecordings/products#78]
Hey, I'm currently on step 6 of your compilers course and I think the quiz linked at the bottom is the wrong one. In the email, its asking me to share how I'd perform the transformation, but the question on the site is the following: "ASTs are cool, but how are they used? Can you think of what comes next? What does Internet Explorer’s JS engine take as input?"

https://www.compilersforhumans.com/answer?question=asts

**Comment by tayiorbeii** [comment]
![ec - c4h - 006 Transform - ConvertKit 2021-09-12 at 11 23 14 AM](https://user-images.githubusercontent.com/2262858/132996908-dc3d1af6-d388-43d3-8f4b-3f97c9631a11.jpg)

https://www.compilersforhumans.com/answer?question=transform

Should be good now!

**Comment by tayiorbeii** [comment]
Just worked through full email course, good to go!
